[alembic]
script_location = %(here)s/migrations
prepend_sys_path = %(here)s/src
file_template = %%(year)04d%%(month)02d%%(day)02d_%%(hour)02d%%(minute)02d_%%(rev)s_%%(slug)s
timezone = UTC
sqlalchemy.url = postgresql+asyncpg://paper_helper:paper_helper@127.0.0.1:5432/paper_helper

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
